server:
  address: ":3000"
  port: 3000

database:
  host: "mysql"
  port: 3306
  user: "root"
  password: "root"
  dbname: "fiber_web"
  max_idle_conns: 10      # 最大空闲连接数
  max_open_conns: 100     # 最大打开连接数
  conn_max_lifetime: "1h" # 连接最大生命周期

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  poolSize: 50
  minIdleConns: 10
  maxRetries: 3

nsq:
  nsqd:
    host: "nsqd"
    port: 4150
  lookupd:
    host: "nsqlookupd"
    port: 4161

app:
  env: "production"
  name: "fiber-web"
  language: "zh"

jwt:
  secret_key: "your-secret-key-here"
  access_token_expiry: "15m"
  refresh_token_expiry: "168h" 