server:
  address: ":3000"
  port: 3000

database:
  multi_db: false
  default:
    host: "mysql"
    port: 3306
    user: "root"
    password: "root"
    dbname: "fiber_web"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: "1h"
  databases:
    default:
      host: "mysql"
      port: 3306
      user: "root"
      password: "root"
      dbname: "fiber_web"
      max_idle_conns: 10
      max_open_conns: 100
      conn_max_lifetime: "1h"
    read:
      host: "mysql-read"
      port: 3306
      user: "readonly"
      password: "readonly"
      dbname: "fiber_web"
      max_idle_conns: 10
      max_open_conns: 100
      conn_max_lifetime: "1h"

redis:
  multi_instance: false
  default:
    host: "redis"
    port: 6379
    password: ""
    db: 0
    pool_size: 50
    min_idle_conns: 10
    max_retries: 3
  instances:
    default:
      host: "redis"
      port: 6379
      password: ""
      db: 0
      pool_size: 50
      min_idle_conns: 10
      max_retries: 3
    cache:
      host: "redis-cache"
      port: 6379
      password: ""
      db: 1
      pool_size: 50
      min_idle_conns: 10
      max_retries: 3

nsq:
  nsqd:
    host: "nsqd"
    port: 4150
  lookupd:
    host: "nsqlookupd"
    port: 4161

app:
  env: "production"
  name: "fiber-web"
  language: "zh"

jwt:
  secret_key: "your-secret-key-here"
  access_token_expiry: "15m"
  refresh_token_expiry: "3m"

log:
  level: "info"
  directory: "/var/log/fiber-web"
  filename: "%Y-%m-%d.log"
  max_size: 10           # 10MB
  max_backups: 5
  max_age: 30           # 30天
  compress: true
  console: false        # 生产环境不输出到控制台