# 用户模块配置
module: user
db_engine: InnoDB
db_charset: utf8mb4

# SQL生成配置
sql_config:
  filename: create_user_tables  # SQL文件名（不含扩展名和时间戳）
  include_timestamp: true      # 是否包含时间戳
  version: v1                  # 版本号

# 实体定义
entities:
  - name: User
    table_name: users
    comment: 用户表
    fields:
      - name: ID
        type: uint
        tag: 'json:"id" gorm:"primarykey"'
        comment: 主键ID
        nullable: false
      - name: Username
        type: string
        tag: 'json:"username" gorm:"size:50;not null"'
        comment: 用户名
        sql_type: VARCHAR(50)
        nullable: false
        unique: [ "username_email" ] # 与 email 组成复合唯一索引
      - name: Email
        type: string
        tag: 'json:"email" gorm:"size:100;not null"'
        comment: 邮箱
        sql_type: VARCHAR(100)
        nullable: false
        unique: [ "username_email" ] # 与 username 组成复合唯一索引
      - name: Password
        type: string
        tag: 'json:"password" gorm:"size:100;not null"'
        comment: 密码
        sql_type: VARCHAR(100)
        nullable: false
      - name: Status
        type: int8
        sql_type: TINYINT(3)
        tag: 'json:"status" gorm:"size:1;default:1"'
        comment: 状态
        nullable: false
        index: [ "status_created" ] # 与 created_at 组成复合索引
      - name: CreatedAt
        type: time.Time
        tag: 'json:"created_at" gorm:"not null"'
        comment: 创建时间
        nullable: false
        index: [ "status_created" ] # 与 status 组成复合索引
      - name: UpdatedAt
        type: time.Time
        tag: 'json:"updated_at" gorm:"not null"'
        comment: 更新时间
        nullable: false
      - name: DeletedAt
        type: gorm.DeletedAt
        tag: 'json:"deleted_at,omitempty" gorm:"index"'
        comment: 删除时间
        nullable: true 