# 用户模块配置
module: user
entities:
  - name: User
    table_name: users
    fields:
      - name: ID
        type: uint
        tag: 'json:"id" gorm:"primarykey"'
        comment: 主键ID
      - name: Username
        type: string
        tag: 'json:"username" gorm:"size:50;not null;unique"'
        comment: 用户名
      - name: Email
        type: string
        tag: 'json:"email" gorm:"size:100;not null;unique"'
        comment: 邮箱
      - name: Password
        type: string
        tag: 'json:"password" gorm:"size:100;not null"'
        comment: 密码
      - name: Status
        type: int
        tag: 'json:"status" gorm:"default:1"'
        comment: 状态
      - name: CreatedAt
        type: time.Time
        tag: 'json:"created_at" gorm:"not null"'
        comment: 创建时间
      - name: UpdatedAt
        type: time.Time
        tag: 'json:"updated_at" gorm:"not null"'
        comment: 更新时间
      - name: DeletedAt
        type: gorm.DeletedAt
        tag: 'json:"deleted_at,omitempty" gorm:"index"'
        comment: 删除时间 